name: Validate renovate config

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 10.34.3
      - name: Use Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 10.34.3
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Validate package.json
        run: pnpm fix:pack
      - name: Validate renovate config
        run: pnpm test
