name: Validate renovate config

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Validate package.json
        run: pnpm fix:pack
      - name: Validate renovate config
        run: pnpm test
